branches:
  only:
  - v2.0
language: node_js
node_js:
- '0.11'
- '0.10'
- '0.8'
before_install:
- npm install -g grunt-cli
script:
- grunt
matrix:
  allow_failures:
  - node_js: '0.11'
deploy:
  provider: npm
  email: me@rreverser.com
  api_key:
    secure: BuwmsjV3RTZKLS29+VMxenHuEt78xyufOcsQxj0c4bGe2/dsmVXTWSQcWtyw05ExtqT8JYrGf/QmTUndCYk0OXJFOgY9fVtVimm2ezInyCgQ1I4oDdiN3KSQ7NpBju5GdGlc/QvJVoCiFud1xxu37bdZpaIUEeM8VjPkjbnAuLw=
  on:
    tags: true
    repo: jDataView/jBinary
    branch: master
  skip_cleanup: true
