branches:
  only:
  - v2.0
language: node_js
node_js:
- '0.11'
- '0.10'
- '0.8'
matrix:
  allow_failures:
  - node_js: '0.11'
before_install:
- npm install -g grunt-cli
script:
- grunt
env:
  global:
    secure: d96Eo9anBBvr+Ucwb92yMp5ZCPi262adt6PsC8uLR+KggH2k8hU9ScAVY9OGttMecKN3dy/OevSbracBGl7C9SP/YTLfGSIO9gaPlPctqn/oF8y1xNzpr0E/KoR/uyLgUPtAWXWxUc4SK6SI3VliRFGDz6iRcVva6iWaDkUp9wY=
notifications:
  webhooks:
    urls:
      - http://rreverser-travis.azurewebsites.net/
    on_failure: never
    on_start: false
