branches:
  only:
  - v2.0
language: node_js
node_js:
- '0.11'
- '0.10'
- '0.8'
matrix:
  fast_finish: true
  allow_failures:
  - node_js: '0.11'
before_install:
- npm install -g grunt-cli
notifications:
  webhooks:
    urls: 'http://rreverser-travis.azurewebsites.net/'
    on_failure: never
    on_start: false
